[package]
name = "wrightomega"
version = "0.1.0"
edition = "2021"

[lib]
name = "wrightomega"

[dependencies]
num-complex = "0.4.4"
num-traits = "0.2.16"
fastapprox = "0.3.1"
criterion = "0.5.1"
rand = "0.8.5"

[features]
default = ["f32"]
f32 = []
f64 = []

[[bench]]
name = "bench"
harness = false